"""Public surface for remote SSH sync and launch workflows."""

from numereng.features.remote_ops.contracts import (
    RemoteBootstrapStatus,
    RemoteConfigPushResult,
    RemoteDoctorResult,
    RemoteExperimentPullFailure,
    RemoteExperimentPullResult,
    RemoteExperimentSyncResult,
    RemoteRepoSyncResult,
    RemoteSyncPolicy,
    RemoteTargetRecord,
    RemoteTrainLaunchResult,
    RemoteVizBootstrapResult,
    RemoteVizBootstrapTargetResult,
)
from numereng.features.remote_ops.service import (
    RemoteExecutionError,
    RemoteOpsError,
    RemoteTargetNotFoundError,
    RemoteValidationError,
    bootstrap_viz_remotes,
    doctor_remote_target,
    list_remote_targets,
    load_viz_bootstrap_state,
    pull_remote_experiment,
    push_remote_config,
    remote_run_train,
    remote_viz_bootstrap_state_path,
    sync_remote_experiment,
    sync_remote_repo,
)

__all__ = [
    "RemoteBootstrapStatus",
    "RemoteConfigPushResult",
    "RemoteDoctorResult",
    "RemoteExperimentPullFailure",
    "RemoteExperimentPullResult",
    "RemoteExecutionError",
    "RemoteExperimentSyncResult",
    "RemoteOpsError",
    "RemoteRepoSyncResult",
    "RemoteSyncPolicy",
    "RemoteTargetNotFoundError",
    "RemoteTargetRecord",
    "RemoteTrainLaunchResult",
    "RemoteValidationError",
    "RemoteVizBootstrapResult",
    "RemoteVizBootstrapTargetResult",
    "bootstrap_viz_remotes",
    "doctor_remote_target",
    "load_viz_bootstrap_state",
    "list_remote_targets",
    "pull_remote_experiment",
    "push_remote_config",
    "remote_run_train",
    "remote_viz_bootstrap_state_path",
    "sync_remote_experiment",
    "sync_remote_repo",
]
