"""Public surface for local run telemetry helpers."""

from numereng.features.telemetry.context import LaunchMetadata, bind_launch_metadata, get_launch_metadata
from numereng.features.telemetry.contracts import (
    LocalResourceSampler,
    LocalRunTelemetrySession,
    ResourceSample,
    RunCancelResult,
    RunLifecycleRecord,
    RunLifecycleRepairResult,
)
from numereng.features.telemetry.service import (
    append_log_line,
    append_resource_sample,
    begin_local_training_session,
    capture_local_resource_sample,
    emit_job_event,
    emit_metric_event,
    emit_stage_event,
    get_run_lifecycle,
    is_cancel_requested,
    mark_job_canceled,
    mark_job_completed,
    mark_job_failed,
    mark_job_running,
    mark_job_stale,
    mark_job_starting,
    reconcile_run_lifecycles,
    request_run_cancel,
    start_local_resource_sampler,
    stop_local_resource_sampler,
)

__all__ = [
    "LaunchMetadata",
    "LocalResourceSampler",
    "LocalRunTelemetrySession",
    "ResourceSample",
    "RunCancelResult",
    "RunLifecycleRecord",
    "RunLifecycleRepairResult",
    "append_log_line",
    "append_resource_sample",
    "begin_local_training_session",
    "bind_launch_metadata",
    "capture_local_resource_sample",
    "emit_job_event",
    "emit_metric_event",
    "emit_stage_event",
    "get_run_lifecycle",
    "get_launch_metadata",
    "is_cancel_requested",
    "mark_job_canceled",
    "mark_job_completed",
    "mark_job_failed",
    "mark_job_running",
    "mark_job_starting",
    "mark_job_stale",
    "reconcile_run_lifecycles",
    "request_run_cancel",
    "start_local_resource_sampler",
    "stop_local_resource_sampler",
]
