"""Strict JSON contracts for the research portfolio (registry + combination study, v1)."""

from numereng.config.research_portfolio.registry import (
    REGISTRY_SCHEMA_VERSION,
    RegistryCandidate,
    RegistryConfig,
    RegistryConfigError,
    RegistryEnvelope,
    RegistryExperiments,
    RegistryLane,
    RegistryLive,
    RegistryPolicy,
    RegistrySupersededExperiment,
    RegistryWallHours,
    load_registry_config,
)
from numereng.config.research_portfolio.study import (
    STUDY_SCHEMA_VERSION,
    FreezeConfig,
    FreezeInference,
    FreezeMember,
    FreezeMetaValidation,
    FreezeNeutralization,
    FreezeSplit,
    StudyConfigError,
    Trial,
    TrialsConfig,
    load_freeze_config,
    load_trials_config,
)

__all__ = [
    "REGISTRY_SCHEMA_VERSION",
    "STUDY_SCHEMA_VERSION",
    "FreezeConfig",
    "FreezeInference",
    "FreezeMember",
    "FreezeMetaValidation",
    "FreezeNeutralization",
    "FreezeSplit",
    "RegistryCandidate",
    "RegistryConfig",
    "RegistryConfigError",
    "RegistryEnvelope",
    "RegistryExperiments",
    "RegistryLane",
    "RegistryLive",
    "RegistryPolicy",
    "RegistrySupersededExperiment",
    "RegistryWallHours",
    "StudyConfigError",
    "Trial",
    "TrialsConfig",
    "load_freeze_config",
    "load_registry_config",
    "load_trials_config",
]
