"""Cloud API modules."""

from numereng.api.cloud.aws import (
    cloud_aws_image_build_push,
    cloud_aws_train_cancel,
    cloud_aws_train_extract,
    cloud_aws_train_logs,
    cloud_aws_train_pull,
    cloud_aws_train_status,
    cloud_aws_train_submit,
)
from numereng.api.cloud.ec2 import (
    cloud_ec2_config_upload,
    cloud_ec2_init_iam,
    cloud_ec2_install,
    cloud_ec2_logs,
    cloud_ec2_package_build_upload,
    cloud_ec2_provision,
    cloud_ec2_pull,
    cloud_ec2_push,
    cloud_ec2_s3_copy,
    cloud_ec2_s3_list,
    cloud_ec2_s3_remove,
    cloud_ec2_setup_data,
    cloud_ec2_status,
    cloud_ec2_terminate,
    cloud_ec2_train_poll,
    cloud_ec2_train_start,
)
from numereng.api.cloud.modal import (
    cloud_modal_data_sync,
    cloud_modal_deploy,
    cloud_modal_train_cancel,
    cloud_modal_train_logs,
    cloud_modal_train_pull,
    cloud_modal_train_status,
    cloud_modal_train_submit,
)

__all__ = [
    "cloud_aws_image_build_push",
    "cloud_aws_train_cancel",
    "cloud_aws_train_extract",
    "cloud_aws_train_logs",
    "cloud_aws_train_pull",
    "cloud_aws_train_status",
    "cloud_aws_train_submit",
    "cloud_ec2_config_upload",
    "cloud_ec2_init_iam",
    "cloud_ec2_install",
    "cloud_ec2_logs",
    "cloud_ec2_package_build_upload",
    "cloud_ec2_provision",
    "cloud_ec2_pull",
    "cloud_ec2_push",
    "cloud_ec2_s3_copy",
    "cloud_ec2_s3_list",
    "cloud_ec2_s3_remove",
    "cloud_ec2_setup_data",
    "cloud_ec2_status",
    "cloud_ec2_terminate",
    "cloud_ec2_train_poll",
    "cloud_ec2_train_start",
    "cloud_modal_data_sync",
    "cloud_modal_deploy",
    "cloud_modal_train_cancel",
    "cloud_modal_train_logs",
    "cloud_modal_train_pull",
    "cloud_modal_train_status",
    "cloud_modal_train_submit",
]
