"""Stable public API surface for numereng consumers."""

from __future__ import annotations

from numereng.api._agentic_research import research_init, research_run, research_status
from numereng.api._baseline import baseline_build
from numereng.api._dataset_tools import dataset_tools_build_downsampled_full
from numereng.api._ensemble import ensemble_build, ensemble_get, ensemble_list
from numereng.api._experiment import (
    experiment_archive,
    experiment_create,
    experiment_get,
    experiment_list,
    experiment_pack,
    experiment_promote,
    experiment_report,
    experiment_score_round,
    experiment_train,
    experiment_unarchive,
)
from numereng.api._factories import (
    _create_cloud_aws_managed_service,
    _create_cloud_ec2_service,
    _create_cloud_modal_service,
    _create_numerai_client,
    _default_dataset_dest_path,
)
from numereng.api._health import get_health, run_bootstrap_check
from numereng.api._hpo import hpo_create, hpo_get, hpo_list, hpo_trials
from numereng.api._monitor import build_monitor_snapshot
from numereng.api._neutralization import neutralize_apply
from numereng.api._numerai import (
    NumeraiForumScrapeResponse,
    download_numerai_dataset,
    get_numerai_current_round,
    list_numerai_datasets,
    list_numerai_models,
    scrape_numerai_forum,
)
from numereng.api._run import cancel_run, get_run_lifecycle, run_training, score_run, submit_predictions
from numereng.api._store import (
    store_doctor,
    store_index_run,
    store_init,
    store_materialize_viz_artifacts,
    store_rebuild,
    store_repair_run_lifecycles,
)
from numereng.api.cloud import (
    cloud_aws_image_build_push,
    cloud_aws_train_cancel,
    cloud_aws_train_extract,
    cloud_aws_train_logs,
    cloud_aws_train_pull,
    cloud_aws_train_status,
    cloud_aws_train_submit,
    cloud_ec2_config_upload,
    cloud_ec2_init_iam,
    cloud_ec2_install,
    cloud_ec2_logs,
    cloud_ec2_package_build_upload,
    cloud_ec2_provision,
    cloud_ec2_pull,
    cloud_ec2_push,
    cloud_ec2_s3_copy,
    cloud_ec2_s3_list,
    cloud_ec2_s3_remove,
    cloud_ec2_setup_data,
    cloud_ec2_status,
    cloud_ec2_terminate,
    cloud_ec2_train_poll,
    cloud_ec2_train_start,
    cloud_modal_data_sync,
    cloud_modal_deploy,
    cloud_modal_train_cancel,
    cloud_modal_train_logs,
    cloud_modal_train_pull,
    cloud_modal_train_status,
    cloud_modal_train_submit,
)
from numereng.api.contracts import (
    BaselineBuildRequest,
    BaselineBuildResponse,
    DatasetToolsBuildDownsampleRequest,
    DatasetToolsBuildDownsampleResponse,
    EnsembleBuildRequest,
    EnsembleComponentResponse,
    EnsembleGetRequest,
    EnsembleListRequest,
    EnsembleListResponse,
    EnsembleMetricResponse,
    EnsembleResponse,
    ExperimentArchiveRequest,
    ExperimentArchiveResponse,
    ExperimentCreateRequest,
    ExperimentGetRequest,
    ExperimentListRequest,
    ExperimentListResponse,
    ExperimentPackRequest,
    ExperimentPackResponse,
    ExperimentPromoteRequest,
    ExperimentPromoteResponse,
    ExperimentReportRequest,
    ExperimentReportResponse,
    ExperimentReportRowResponse,
    ExperimentResponse,
    ExperimentScoreRoundRequest,
    ExperimentScoreRoundResponse,
    ExperimentStatus,
    ExperimentTrainRequest,
    ExperimentTrainResponse,
    HealthResponse,
    HpoStudyCreateRequest,
    HpoStudyGetRequest,
    HpoStudyListRequest,
    HpoStudyListResponse,
    HpoStudyResponse,
    HpoStudyTrialsRequest,
    HpoStudyTrialsResponse,
    HpoTrialResponse,
    MonitorExperimentResponse,
    MonitorLiveExperimentResponse,
    MonitorLiveRunResponse,
    MonitorRecentActivityResponse,
    MonitorSnapshotRequest,
    MonitorSnapshotResponse,
    MonitorSourceResponse,
    MonitorSummaryResponse,
    NeutralizationMode,
    NeutralizeRequest,
    NeutralizeResponse,
    NumeraiCurrentRoundRequest,
    NumeraiCurrentRoundResponse,
    NumeraiDatasetDownloadRequest,
    NumeraiDatasetDownloadResponse,
    NumeraiDatasetListRequest,
    NumeraiDatasetListResponse,
    NumeraiModelsRequest,
    NumeraiModelsResponse,
    NumeraiTournament,
    PostTrainingScoringPolicy,
    ResearchBestRunResponse,
    ResearchInitRequest,
    ResearchInitResponse,
    ResearchPhaseResponse,
    ResearchRoundResponse,
    ResearchRunRequest,
    ResearchRunResponse,
    ResearchStatusRequest,
    ResearchStatusResponse,
    ResearchStrategy,
    ResearchSupervisorStatus,
    RunCancelRequest,
    RunCancelResponse,
    RunLifecycleRequest,
    RunLifecycleResponse,
    ScoreRunRequest,
    ScoreRunResponse,
    StoreDoctorRequest,
    StoreDoctorResponse,
    StoreIndexRequest,
    StoreIndexResponse,
    StoreInitRequest,
    StoreInitResponse,
    StoreMaterializeVizArtifactsFailureResponse,
    StoreMaterializeVizArtifactsRequest,
    StoreMaterializeVizArtifactsResponse,
    StoreRebuildFailureResponse,
    StoreRebuildRequest,
    StoreRebuildResponse,
    StoreRunLifecycleRepairRequest,
    StoreRunLifecycleRepairResponse,
    SubmissionRequest,
    SubmissionResponse,
    TrainingEngineMode,
    TrainingProfile,
    TrainRunRequest,
    TrainRunResponse,
)
from numereng.features.agentic_research import get_research_status as get_research_program_status
from numereng.features.agentic_research import init_research as init_research_program
from numereng.features.agentic_research import run_research as run_research_program
from numereng.features.baseline import build_baseline as build_baseline_record
from numereng.features.cloud.aws import (
    AwsImageBuildPushRequest,
    AwsTrainCancelRequest,
    AwsTrainExtractRequest,
    AwsTrainLogsRequest,
    AwsTrainPullRequest,
    AwsTrainStatusRequest,
    AwsTrainSubmitRequest,
    CloudAwsResponse,
    CloudEc2Response,
    Ec2ConfigUploadRequest,
    Ec2InitIamRequest,
    Ec2InstallRequest,
    Ec2LogsRequest,
    Ec2PackageBuildUploadRequest,
    Ec2ProvisionRequest,
    Ec2PullRequest,
    Ec2PushRequest,
    Ec2S3CopyRequest,
    Ec2S3ListRequest,
    Ec2S3RemoveRequest,
    Ec2SetupDataRequest,
    Ec2StatusRequest,
    Ec2TerminateRequest,
    Ec2TrainPollRequest,
    Ec2TrainStartRequest,
)
from numereng.features.cloud.modal import (
    CloudModalResponse,
    ModalDataSyncRequest,
    ModalDataSyncResult,
    ModalDeployRequest,
    ModalDeployResult,
    ModalTrainCancelRequest,
    ModalTrainLogsRequest,
    ModalTrainPullRequest,
    ModalTrainStatusRequest,
    ModalTrainSubmitRequest,
)
from numereng.features.ensemble import build_ensemble as build_ensemble_record
from numereng.features.ensemble import get_ensemble_view as get_ensemble_record_api
from numereng.features.ensemble import list_ensembles_view as list_ensemble_records_api
from numereng.features.experiments import archive_experiment as archive_experiment_record
from numereng.features.experiments import create_experiment as create_experiment_record
from numereng.features.experiments import get_experiment as get_experiment_record
from numereng.features.experiments import list_experiments as list_experiment_records
from numereng.features.experiments import pack_experiment as pack_experiment_record
from numereng.features.experiments import promote_experiment as promote_experiment_record
from numereng.features.experiments import report_experiment as report_experiment_record
from numereng.features.experiments import score_experiment_round as score_experiment_round_record
from numereng.features.experiments import train_experiment as train_experiment_record
from numereng.features.experiments import unarchive_experiment as unarchive_experiment_record
from numereng.features.feature_neutralization import neutralize_predictions_file as neutralize_prediction_artifact
from numereng.features.feature_neutralization import neutralize_run_predictions as neutralize_run_prediction_artifact
from numereng.features.hpo import create_study as hpo_create_study
from numereng.features.hpo import get_study_trials_view as hpo_get_study_trials
from numereng.features.hpo import get_study_view as hpo_get_study
from numereng.features.hpo import list_studies_view as hpo_list_studies
from numereng.features.store import doctor_store, index_run, init_store_db, materialize_viz_artifacts, rebuild_run_index
from numereng.features.submission import submit_predictions_file, submit_run_predictions
from numereng.features.telemetry import get_run_lifecycle as get_run_lifecycle_record
from numereng.features.telemetry import reconcile_run_lifecycles as reconcile_run_lifecycles_record
from numereng.features.telemetry import request_run_cancel as request_run_cancel_record
from numereng.features.training import run_training as run_training_pipeline
from numereng.features.training import score_run as score_run_pipeline
from numereng.platform.errors import PackageError
from numereng.platform.forum_scraper import scrape_forum_posts

__all__ = [
    "AwsImageBuildPushRequest",
    "AwsTrainCancelRequest",
    "AwsTrainExtractRequest",
    "AwsTrainLogsRequest",
    "AwsTrainPullRequest",
    "AwsTrainStatusRequest",
    "AwsTrainSubmitRequest",
    "BaselineBuildRequest",
    "BaselineBuildResponse",
    "ExperimentArchiveRequest",
    "ExperimentArchiveResponse",
    "CloudAwsResponse",
    "CloudEc2Response",
    "CloudModalResponse",
    "DatasetToolsBuildDownsampleRequest",
    "DatasetToolsBuildDownsampleResponse",
    "EnsembleBuildRequest",
    "EnsembleComponentResponse",
    "EnsembleGetRequest",
    "EnsembleListRequest",
    "EnsembleListResponse",
    "EnsembleMetricResponse",
    "EnsembleResponse",
    "ExperimentCreateRequest",
    "ExperimentGetRequest",
    "ExperimentListRequest",
    "ExperimentListResponse",
    "ExperimentPackRequest",
    "ExperimentPackResponse",
    "ExperimentPromoteRequest",
    "ExperimentPromoteResponse",
    "ExperimentReportRequest",
    "ExperimentReportResponse",
    "ExperimentReportRowResponse",
    "ExperimentScoreRoundRequest",
    "ExperimentScoreRoundResponse",
    "ExperimentResponse",
    "ExperimentStatus",
    "ExperimentTrainRequest",
    "ExperimentTrainResponse",
    "ResearchBestRunResponse",
    "ResearchInitRequest",
    "ResearchInitResponse",
    "ResearchPhaseResponse",
    "ResearchRoundResponse",
    "ResearchRunRequest",
    "ResearchRunResponse",
    "ResearchStatusRequest",
    "ResearchStatusResponse",
    "ResearchStrategy",
    "ResearchSupervisorStatus",
    "RunCancelRequest",
    "RunCancelResponse",
    "RunLifecycleRequest",
    "RunLifecycleResponse",
    "Ec2ConfigUploadRequest",
    "Ec2InitIamRequest",
    "Ec2InstallRequest",
    "Ec2LogsRequest",
    "Ec2PackageBuildUploadRequest",
    "Ec2ProvisionRequest",
    "Ec2PullRequest",
    "Ec2PushRequest",
    "Ec2S3CopyRequest",
    "Ec2S3ListRequest",
    "Ec2S3RemoveRequest",
    "Ec2SetupDataRequest",
    "Ec2StatusRequest",
    "Ec2TerminateRequest",
    "Ec2TrainPollRequest",
    "Ec2TrainStartRequest",
    "HealthResponse",
    "HpoStudyCreateRequest",
    "HpoStudyGetRequest",
    "HpoStudyListRequest",
    "HpoStudyListResponse",
    "HpoStudyResponse",
    "HpoStudyTrialsRequest",
    "HpoStudyTrialsResponse",
    "HpoTrialResponse",
    "NumeraiCurrentRoundRequest",
    "NumeraiCurrentRoundResponse",
    "NumeraiDatasetDownloadRequest",
    "NumeraiDatasetDownloadResponse",
    "NumeraiDatasetListRequest",
    "NumeraiDatasetListResponse",
    "NumeraiModelsRequest",
    "NumeraiModelsResponse",
    "NumeraiForumScrapeResponse",
    "NumeraiTournament",
    "ScoreRunRequest",
    "ScoreRunResponse",
    "NeutralizationMode",
    "NeutralizeRequest",
    "NeutralizeResponse",
    "PackageError",
    "ModalDataSyncRequest",
    "ModalDataSyncResult",
    "ModalDeployRequest",
    "ModalDeployResult",
    "MonitorExperimentResponse",
    "MonitorLiveExperimentResponse",
    "MonitorLiveRunResponse",
    "MonitorRecentActivityResponse",
    "MonitorSnapshotRequest",
    "MonitorSnapshotResponse",
    "MonitorSourceResponse",
    "MonitorSummaryResponse",
    "ModalTrainCancelRequest",
    "ModalTrainLogsRequest",
    "ModalTrainPullRequest",
    "ModalTrainStatusRequest",
    "ModalTrainSubmitRequest",
    "SubmissionRequest",
    "SubmissionResponse",
    "StoreDoctorRequest",
    "StoreDoctorResponse",
    "StoreIndexRequest",
    "StoreIndexResponse",
    "StoreInitRequest",
    "StoreInitResponse",
    "StoreMaterializeVizArtifactsFailureResponse",
    "StoreMaterializeVizArtifactsRequest",
    "StoreMaterializeVizArtifactsResponse",
    "StoreRunLifecycleRepairRequest",
    "StoreRunLifecycleRepairResponse",
    "StoreRebuildFailureResponse",
    "StoreRebuildRequest",
    "StoreRebuildResponse",
    "TrainingEngineMode",
    "PostTrainingScoringPolicy",
    "TrainingProfile",
    "TrainRunRequest",
    "TrainRunResponse",
    "cloud_ec2_config_upload",
    "cloud_ec2_init_iam",
    "cloud_ec2_install",
    "cloud_ec2_logs",
    "cloud_ec2_package_build_upload",
    "cloud_ec2_provision",
    "cloud_ec2_pull",
    "cloud_ec2_push",
    "cloud_ec2_s3_copy",
    "cloud_ec2_s3_list",
    "cloud_ec2_s3_remove",
    "cloud_ec2_setup_data",
    "cloud_ec2_status",
    "cloud_ec2_terminate",
    "cloud_ec2_train_poll",
    "cloud_ec2_train_start",
    "cloud_aws_image_build_push",
    "cloud_aws_train_cancel",
    "cloud_aws_train_extract",
    "cloud_aws_train_logs",
    "cloud_aws_train_pull",
    "cloud_aws_train_status",
    "cloud_aws_train_submit",
    "cloud_modal_data_sync",
    "cloud_modal_deploy",
    "cloud_modal_train_cancel",
    "cloud_modal_train_logs",
    "cloud_modal_train_pull",
    "cloud_modal_train_status",
    "cloud_modal_train_submit",
    "_create_cloud_aws_managed_service",
    "_create_cloud_ec2_service",
    "_create_cloud_modal_service",
    "_create_numerai_client",
    "_default_dataset_dest_path",
    "archive_experiment_record",
    "baseline_build",
    "build_baseline_record",
    "cancel_run",
    "create_experiment_record",
    "dataset_tools_build_downsampled_full",
    "doctor_store",
    "download_numerai_dataset",
    "ensemble_build",
    "ensemble_get",
    "ensemble_list",
    "experiment_archive",
    "experiment_create",
    "experiment_get",
    "experiment_list",
    "experiment_pack",
    "experiment_promote",
    "experiment_report",
    "experiment_score_round",
    "experiment_train",
    "experiment_unarchive",
    "get_experiment_record",
    "get_health",
    "get_numerai_current_round",
    "get_run_lifecycle",
    "index_run",
    "init_store_db",
    "hpo_create",
    "hpo_get",
    "hpo_list",
    "hpo_trials",
    "neutralize_apply",
    "hpo_create_study",
    "hpo_get_study",
    "hpo_get_study_trials",
    "hpo_list_studies",
    "list_experiment_records",
    "build_ensemble_record",
    "build_monitor_snapshot",
    "get_ensemble_record_api",
    "get_run_lifecycle_record",
    "list_ensemble_records_api",
    "list_numerai_datasets",
    "list_numerai_models",
    "reconcile_run_lifecycles_record",
    "request_run_cancel_record",
    "scrape_forum_posts",
    "scrape_numerai_forum",
    "promote_experiment_record",
    "pack_experiment_record",
    "rebuild_run_index",
    "report_experiment_record",
    "research_init",
    "research_run",
    "research_status",
    "score_experiment_round_record",
    "score_run_pipeline",
    "run_training_pipeline",
    "score_run",
    "store_doctor",
    "store_index_run",
    "store_init",
    "store_materialize_viz_artifacts",
    "store_repair_run_lifecycles",
    "store_rebuild",
    "run_training",
    "run_bootstrap_check",
    "init_research_program",
    "get_research_program_status",
    "run_research_program",
    "neutralize_prediction_artifact",
    "neutralize_run_prediction_artifact",
    "submit_predictions_file",
    "submit_predictions",
    "submit_run_predictions",
    "materialize_viz_artifacts",
    "train_experiment_record",
    "unarchive_experiment_record",
]
