"""Stable public API surface for numereng consumers."""

from __future__ import annotations

from importlib import import_module

from numereng.api.contracts import (
    BaselineBuildRequest,
    BaselineBuildResponse,
    DatasetToolsBuildDownsampleRequest,
    DatasetToolsBuildDownsampleResponse,
    DocsSyncRequest,
    DocsSyncResponse,
    EnsembleBuildRequest,
    EnsembleComponentResponse,
    EnsembleGetRequest,
    EnsembleListRequest,
    EnsembleListResponse,
    EnsembleMetricResponse,
    EnsembleResponse,
    EnsembleSelectionSourceRuleRequest,
    EnsembleSelectionWinnerResponse,
    EnsembleSelectRequest,
    EnsembleSelectResponse,
    ExperimentArchiveRequest,
    ExperimentArchiveResponse,
    ExperimentCreateRequest,
    ExperimentGetRequest,
    ExperimentListRequest,
    ExperimentListResponse,
    ExperimentPackRequest,
    ExperimentPackResponse,
    ExperimentPromoteRequest,
    ExperimentPromoteResponse,
    ExperimentReportRequest,
    ExperimentReportResponse,
    ExperimentReportRowResponse,
    ExperimentResponse,
    ExperimentRunPlanRequest,
    ExperimentRunPlanResponse,
    ExperimentRunPlanWindowResponse,
    ExperimentScoreRoundRequest,
    ExperimentScoreRoundResponse,
    ExperimentStatus,
    ExperimentTrainRequest,
    ExperimentTrainResponse,
    HealthResponse,
    HpoNeutralizationRequest,
    HpoObjectiveRequest,
    HpoPlateauRequest,
    HpoSamplerRequest,
    HpoSearchSpaceSpecRequest,
    HpoStoppingRequest,
    HpoStudyCreateRequest,
    HpoStudyGetRequest,
    HpoStudyListRequest,
    HpoStudyListResponse,
    HpoStudyResponse,
    HpoStudySpecResponse,
    HpoStudyTrialsRequest,
    HpoStudyTrialsResponse,
    HpoTrialResponse,
    MonitorExperimentResponse,
    MonitorLiveExperimentResponse,
    MonitorLiveRunResponse,
    MonitorRecentActivityResponse,
    MonitorSnapshotRequest,
    MonitorSnapshotResponse,
    MonitorSourceResponse,
    MonitorSummaryResponse,
    NeutralizationMode,
    NeutralizeRequest,
    NeutralizeResponse,
    NumeraiCurrentRoundRequest,
    NumeraiCurrentRoundResponse,
    NumeraiDatasetDownloadRequest,
    NumeraiDatasetDownloadResponse,
    NumeraiDatasetListRequest,
    NumeraiDatasetListResponse,
    NumeraiModelsRequest,
    NumeraiModelsResponse,
    NumeraiTournament,
    PostTrainingScoringPolicy,
    RemoteConfigPushRequest,
    RemoteConfigPushResponse,
    RemoteDoctorRequest,
    RemoteDoctorResponse,
    RemoteExperimentLaunchRequest,
    RemoteExperimentLaunchResponse,
    RemoteExperimentMaintainRequest,
    RemoteExperimentMaintainResponse,
    RemoteExperimentPullFailureResponse,
    RemoteExperimentPullRequest,
    RemoteExperimentPullResponse,
    RemoteExperimentStatusRequest,
    RemoteExperimentStatusResponse,
    RemoteExperimentStopRequest,
    RemoteExperimentStopResponse,
    RemoteExperimentSyncRequest,
    RemoteExperimentSyncResponse,
    RemoteRepoSyncRequest,
    RemoteRepoSyncResponse,
    RemoteTargetListRequest,
    RemoteTargetListResponse,
    RemoteTargetResponse,
    RemoteTrainLaunchRequest,
    RemoteTrainLaunchResponse,
    RemoteVizBootstrapRequest,
    RemoteVizBootstrapResponse,
    RemoteVizBootstrapTargetResponse,
    ResearchBestRunResponse,
    ResearchInitRequest,
    ResearchInitResponse,
    ResearchPhaseResponse,
    ResearchPlannerContract,
    ResearchProgramCatalogEntryResponse,
    ResearchProgramConfigPolicyResponse,
    ResearchProgramListRequest,
    ResearchProgramListResponse,
    ResearchProgramMetricPolicyResponse,
    ResearchProgramPhaseResponse,
    ResearchProgramRoundPolicyResponse,
    ResearchProgramShowRequest,
    ResearchProgramShowResponse,
    ResearchProgramSource,
    ResearchRoundResponse,
    ResearchRunRequest,
    ResearchRunResponse,
    ResearchStatusRequest,
    ResearchStatusResponse,
    ResearchSupervisorStatus,
    RunCancelRequest,
    RunCancelResponse,
    RunLifecycleRequest,
    RunLifecycleResponse,
    ScoreRunRequest,
    ScoreRunResponse,
    ServeBlendRuleRequest,
    ServeComponentInspectionResponse,
    ServeComponentRequest,
    ServeLiveBuildRequest,
    ServeLiveBuildResponse,
    ServeLiveSubmitRequest,
    ServeLiveSubmitResponse,
    ServeNeutralizationRequest,
    ServePackageCreateRequest,
    ServePackageInspectRequest,
    ServePackageInspectResponse,
    ServePackageListRequest,
    ServePackageListResponse,
    ServePackageResponse,
    ServePickleBuildRequest,
    ServePickleBuildResponse,
    ServePickleUploadRequest,
    ServePickleUploadResponse,
    StoreDoctorRequest,
    StoreDoctorResponse,
    StoreIndexRequest,
    StoreIndexResponse,
    StoreInitRequest,
    StoreInitResponse,
    StoreMaterializeVizArtifactsFailureResponse,
    StoreMaterializeVizArtifactsRequest,
    StoreMaterializeVizArtifactsResponse,
    StoreRebuildFailureResponse,
    StoreRebuildRequest,
    StoreRebuildResponse,
    StoreRunExecutionBackfillRequest,
    StoreRunExecutionBackfillResponse,
    StoreRunLifecycleRepairRequest,
    StoreRunLifecycleRepairResponse,
    SubmissionRequest,
    SubmissionResponse,
    TrainingEngineMode,
    TrainingProfile,
    TrainRunRequest,
    TrainRunResponse,
    VizAppRequest,
)
from numereng.platform.errors import PackageError

_LAZY_EXPORTS: dict[str, tuple[str, str]] = {
    "baseline_build": ("numereng.api._baseline", "baseline_build"),
    "dataset_tools_build_downsampled_full": (
        "numereng.api._dataset_tools",
        "dataset_tools_build_downsampled_full",
    ),
    "sync_docs": ("numereng.api._docs", "sync_docs"),
    "ensemble_build": ("numereng.api._ensemble", "ensemble_build"),
    "ensemble_get": ("numereng.api._ensemble", "ensemble_get"),
    "ensemble_list": ("numereng.api._ensemble", "ensemble_list"),
    "ensemble_select": ("numereng.api._ensemble", "ensemble_select"),
    "experiment_archive": ("numereng.api._experiment", "experiment_archive"),
    "experiment_create": ("numereng.api._experiment", "experiment_create"),
    "experiment_get": ("numereng.api._experiment", "experiment_get"),
    "experiment_list": ("numereng.api._experiment", "experiment_list"),
    "experiment_pack": ("numereng.api._experiment", "experiment_pack"),
    "experiment_promote": ("numereng.api._experiment", "experiment_promote"),
    "experiment_report": ("numereng.api._experiment", "experiment_report"),
    "experiment_run_plan": ("numereng.api._experiment", "experiment_run_plan"),
    "experiment_score_round": ("numereng.api._experiment", "experiment_score_round"),
    "experiment_train": ("numereng.api._experiment", "experiment_train"),
    "experiment_unarchive": ("numereng.api._experiment", "experiment_unarchive"),
    "_create_cloud_aws_managed_service": ("numereng.api._factories", "_create_cloud_aws_managed_service"),
    "_create_cloud_ec2_service": ("numereng.api._factories", "_create_cloud_ec2_service"),
    "_create_cloud_modal_service": ("numereng.api._factories", "_create_cloud_modal_service"),
    "_create_numerai_client": ("numereng.api._factories", "_create_numerai_client"),
    "_default_dataset_dest_path": ("numereng.api._factories", "_default_dataset_dest_path"),
    "get_health": ("numereng.api._health", "get_health"),
    "run_bootstrap_check": ("numereng.api._health", "run_bootstrap_check"),
    "hpo_create": ("numereng.api._hpo", "hpo_create"),
    "hpo_get": ("numereng.api._hpo", "hpo_get"),
    "hpo_list": ("numereng.api._hpo", "hpo_list"),
    "hpo_trials": ("numereng.api._hpo", "hpo_trials"),
    "build_monitor_snapshot": ("numereng.api._monitor", "build_monitor_snapshot"),
    "neutralize_apply": ("numereng.api._neutralization", "neutralize_apply"),
    "NumeraiForumScrapeResponse": ("numereng.api._numerai", "NumeraiForumScrapeResponse"),
    "download_numerai_dataset": ("numereng.api._numerai", "download_numerai_dataset"),
    "get_numerai_current_round": ("numereng.api._numerai", "get_numerai_current_round"),
    "list_numerai_datasets": ("numereng.api._numerai", "list_numerai_datasets"),
    "list_numerai_models": ("numereng.api._numerai", "list_numerai_models"),
    "scrape_numerai_forum": ("numereng.api._numerai", "scrape_numerai_forum"),
    "serve_live_build": ("numereng.api._serving", "serve_live_build"),
    "serve_live_submit": ("numereng.api._serving", "serve_live_submit"),
    "serve_package_create": ("numereng.api._serving", "serve_package_create"),
    "serve_package_inspect": ("numereng.api._serving", "serve_package_inspect"),
    "serve_package_list": ("numereng.api._serving", "serve_package_list"),
    "serve_package_score": ("numereng.api._serving", "serve_package_score"),
    "serve_package_sync_diagnostics": ("numereng.api._serving", "serve_package_sync_diagnostics"),
    "serve_pickle_build": ("numereng.api._serving", "serve_pickle_build"),
    "serve_pickle_upload": ("numereng.api._serving", "serve_pickle_upload"),
    "ServePackageScoreRequest": ("numereng.api.contracts", "ServePackageScoreRequest"),
    "ServePackageScoreResponse": ("numereng.api.contracts", "ServePackageScoreResponse"),
    "ServePackageSyncDiagnosticsRequest": ("numereng.api.contracts", "ServePackageSyncDiagnosticsRequest"),
    "ServePackageSyncDiagnosticsResponse": ("numereng.api.contracts", "ServePackageSyncDiagnosticsResponse"),
    "remote_bootstrap_viz": ("numereng.api._remote", "remote_bootstrap_viz"),
    "remote_config_push": ("numereng.api._remote", "remote_config_push"),
    "remote_doctor": ("numereng.api._remote", "remote_doctor"),
    "remote_experiment_launch": ("numereng.api._remote", "remote_experiment_launch"),
    "remote_experiment_maintain": ("numereng.api._remote", "remote_experiment_maintain"),
    "remote_experiment_pull": ("numereng.api._remote", "remote_experiment_pull"),
    "remote_experiment_status": ("numereng.api._remote", "remote_experiment_status"),
    "remote_experiment_stop": ("numereng.api._remote", "remote_experiment_stop"),
    "remote_experiment_sync": ("numereng.api._remote", "remote_experiment_sync"),
    "remote_list_targets": ("numereng.api._remote", "remote_list_targets"),
    "remote_repo_sync": ("numereng.api._remote", "remote_repo_sync"),
    "remote_train_launch": ("numereng.api._remote", "remote_train_launch"),
    "cancel_run": ("numereng.api._run", "cancel_run"),
    "get_run_lifecycle": ("numereng.api._run", "get_run_lifecycle"),
    "run_training": ("numereng.api._run", "run_training"),
    "score_run": ("numereng.api._run", "score_run"),
    "submit_predictions": ("numereng.api._run", "submit_predictions"),
    "store_backfill_run_execution": ("numereng.api._store", "store_backfill_run_execution"),
    "store_doctor": ("numereng.api._store", "store_doctor"),
    "store_index_run": ("numereng.api._store", "store_index_run"),
    "store_init": ("numereng.api._store", "store_init"),
    "store_materialize_viz_artifacts": ("numereng.api._store", "store_materialize_viz_artifacts"),
    "store_rebuild": ("numereng.api._store", "store_rebuild"),
    "store_repair_run_lifecycles": ("numereng.api._store", "store_repair_run_lifecycles"),
    "create_viz_app": ("numereng.api._viz", "create_viz_app"),
    "cloud_aws_image_build_push": ("numereng.api.cloud", "cloud_aws_image_build_push"),
    "cloud_aws_train_cancel": ("numereng.api.cloud", "cloud_aws_train_cancel"),
    "cloud_aws_train_extract": ("numereng.api.cloud", "cloud_aws_train_extract"),
    "cloud_aws_train_logs": ("numereng.api.cloud", "cloud_aws_train_logs"),
    "cloud_aws_train_pull": ("numereng.api.cloud", "cloud_aws_train_pull"),
    "cloud_aws_train_status": ("numereng.api.cloud", "cloud_aws_train_status"),
    "cloud_aws_train_submit": ("numereng.api.cloud", "cloud_aws_train_submit"),
    "cloud_ec2_config_upload": ("numereng.api.cloud", "cloud_ec2_config_upload"),
    "cloud_ec2_init_iam": ("numereng.api.cloud", "cloud_ec2_init_iam"),
    "cloud_ec2_install": ("numereng.api.cloud", "cloud_ec2_install"),
    "cloud_ec2_logs": ("numereng.api.cloud", "cloud_ec2_logs"),
    "cloud_ec2_package_build_upload": ("numereng.api.cloud", "cloud_ec2_package_build_upload"),
    "cloud_ec2_provision": ("numereng.api.cloud", "cloud_ec2_provision"),
    "cloud_ec2_pull": ("numereng.api.cloud", "cloud_ec2_pull"),
    "cloud_ec2_push": ("numereng.api.cloud", "cloud_ec2_push"),
    "cloud_ec2_s3_copy": ("numereng.api.cloud", "cloud_ec2_s3_copy"),
    "cloud_ec2_s3_list": ("numereng.api.cloud", "cloud_ec2_s3_list"),
    "cloud_ec2_s3_remove": ("numereng.api.cloud", "cloud_ec2_s3_remove"),
    "cloud_ec2_setup_data": ("numereng.api.cloud", "cloud_ec2_setup_data"),
    "cloud_ec2_status": ("numereng.api.cloud", "cloud_ec2_status"),
    "cloud_ec2_terminate": ("numereng.api.cloud", "cloud_ec2_terminate"),
    "cloud_ec2_train_poll": ("numereng.api.cloud", "cloud_ec2_train_poll"),
    "cloud_ec2_train_start": ("numereng.api.cloud", "cloud_ec2_train_start"),
    "cloud_modal_data_sync": ("numereng.api.cloud", "cloud_modal_data_sync"),
    "cloud_modal_deploy": ("numereng.api.cloud", "cloud_modal_deploy"),
    "cloud_modal_train_cancel": ("numereng.api.cloud", "cloud_modal_train_cancel"),
    "cloud_modal_train_logs": ("numereng.api.cloud", "cloud_modal_train_logs"),
    "cloud_modal_train_pull": ("numereng.api.cloud", "cloud_modal_train_pull"),
    "cloud_modal_train_status": ("numereng.api.cloud", "cloud_modal_train_status"),
    "cloud_modal_train_submit": ("numereng.api.cloud", "cloud_modal_train_submit"),
    "build_baseline_record": ("numereng.features.baseline", "build_baseline"),
    "AwsImageBuildPushRequest": ("numereng.features.cloud.aws", "AwsImageBuildPushRequest"),
    "AwsTrainCancelRequest": ("numereng.features.cloud.aws", "AwsTrainCancelRequest"),
    "AwsTrainExtractRequest": ("numereng.features.cloud.aws", "AwsTrainExtractRequest"),
    "AwsTrainLogsRequest": ("numereng.features.cloud.aws", "AwsTrainLogsRequest"),
    "AwsTrainPullRequest": ("numereng.features.cloud.aws", "AwsTrainPullRequest"),
    "AwsTrainStatusRequest": ("numereng.features.cloud.aws", "AwsTrainStatusRequest"),
    "AwsTrainSubmitRequest": ("numereng.features.cloud.aws", "AwsTrainSubmitRequest"),
    "CloudAwsResponse": ("numereng.features.cloud.aws", "CloudAwsResponse"),
    "CloudEc2Response": ("numereng.features.cloud.aws", "CloudEc2Response"),
    "Ec2ConfigUploadRequest": ("numereng.features.cloud.aws", "Ec2ConfigUploadRequest"),
    "Ec2InitIamRequest": ("numereng.features.cloud.aws", "Ec2InitIamRequest"),
    "Ec2InstallRequest": ("numereng.features.cloud.aws", "Ec2InstallRequest"),
    "Ec2LogsRequest": ("numereng.features.cloud.aws", "Ec2LogsRequest"),
    "Ec2PackageBuildUploadRequest": ("numereng.features.cloud.aws", "Ec2PackageBuildUploadRequest"),
    "Ec2ProvisionRequest": ("numereng.features.cloud.aws", "Ec2ProvisionRequest"),
    "Ec2PullRequest": ("numereng.features.cloud.aws", "Ec2PullRequest"),
    "Ec2PushRequest": ("numereng.features.cloud.aws", "Ec2PushRequest"),
    "Ec2S3CopyRequest": ("numereng.features.cloud.aws", "Ec2S3CopyRequest"),
    "Ec2S3ListRequest": ("numereng.features.cloud.aws", "Ec2S3ListRequest"),
    "Ec2S3RemoveRequest": ("numereng.features.cloud.aws", "Ec2S3RemoveRequest"),
    "Ec2SetupDataRequest": ("numereng.features.cloud.aws", "Ec2SetupDataRequest"),
    "Ec2StatusRequest": ("numereng.features.cloud.aws", "Ec2StatusRequest"),
    "Ec2TerminateRequest": ("numereng.features.cloud.aws", "Ec2TerminateRequest"),
    "Ec2TrainPollRequest": ("numereng.features.cloud.aws", "Ec2TrainPollRequest"),
    "Ec2TrainStartRequest": ("numereng.features.cloud.aws", "Ec2TrainStartRequest"),
    "CloudModalResponse": ("numereng.features.cloud.modal", "CloudModalResponse"),
    "ModalDataSyncRequest": ("numereng.features.cloud.modal", "ModalDataSyncRequest"),
    "ModalDataSyncResult": ("numereng.features.cloud.modal", "ModalDataSyncResult"),
    "ModalDeployRequest": ("numereng.features.cloud.modal", "ModalDeployRequest"),
    "ModalDeployResult": ("numereng.features.cloud.modal", "ModalDeployResult"),
    "ModalTrainCancelRequest": ("numereng.features.cloud.modal", "ModalTrainCancelRequest"),
    "ModalTrainLogsRequest": ("numereng.features.cloud.modal", "ModalTrainLogsRequest"),
    "ModalTrainPullRequest": ("numereng.features.cloud.modal", "ModalTrainPullRequest"),
    "ModalTrainStatusRequest": ("numereng.features.cloud.modal", "ModalTrainStatusRequest"),
    "ModalTrainSubmitRequest": ("numereng.features.cloud.modal", "ModalTrainSubmitRequest"),
    "build_ensemble_record": ("numereng.features.ensemble", "build_ensemble"),
    "get_ensemble_record_api": ("numereng.features.ensemble", "get_ensemble_view"),
    "list_ensemble_records_api": ("numereng.features.ensemble", "list_ensembles_view"),
    "select_ensemble_record": ("numereng.features.ensemble", "select_ensemble"),
    "archive_experiment_record": ("numereng.features.experiments", "archive_experiment"),
    "create_experiment_record": ("numereng.features.experiments", "create_experiment"),
    "get_experiment_record": ("numereng.features.experiments", "get_experiment"),
    "list_experiment_records": ("numereng.features.experiments", "list_experiments"),
    "pack_experiment_record": ("numereng.features.experiments", "pack_experiment"),
    "promote_experiment_record": ("numereng.features.experiments", "promote_experiment"),
    "report_experiment_record": ("numereng.features.experiments", "report_experiment"),
    "run_experiment_plan_record": ("numereng.features.experiments", "run_experiment_plan"),
    "score_experiment_round_record": ("numereng.features.experiments", "score_experiment_round"),
    "train_experiment_record": ("numereng.features.experiments", "train_experiment"),
    "unarchive_experiment_record": ("numereng.features.experiments", "unarchive_experiment"),
    "neutralize_prediction_artifact": (
        "numereng.features.feature_neutralization",
        "neutralize_predictions_file",
    ),
    "neutralize_run_prediction_artifact": (
        "numereng.features.feature_neutralization",
        "neutralize_run_predictions",
    ),
    "hpo_create_study": ("numereng.features.hpo", "create_study"),
    "hpo_get_study_trials": ("numereng.features.hpo", "get_study_trials_view"),
    "hpo_get_study": ("numereng.features.hpo", "get_study_view"),
    "hpo_list_studies": ("numereng.features.hpo", "list_studies_view"),
    "backfill_run_execution": ("numereng.features.store", "backfill_run_execution"),
    "doctor_store": ("numereng.features.store", "doctor_store"),
    "index_run": ("numereng.features.store", "index_run"),
    "init_store_db": ("numereng.features.store", "init_store_db"),
    "materialize_viz_artifacts": ("numereng.features.store", "materialize_viz_artifacts"),
    "rebuild_run_index": ("numereng.features.store", "rebuild_run_index"),
    "submit_predictions_file": ("numereng.features.submission", "submit_predictions_file"),
    "submit_run_predictions": ("numereng.features.submission", "submit_run_predictions"),
    "get_run_lifecycle_record": ("numereng.features.telemetry", "get_run_lifecycle"),
    "reconcile_run_lifecycles_record": ("numereng.features.telemetry", "reconcile_run_lifecycles"),
    "request_run_cancel_record": ("numereng.features.telemetry", "request_run_cancel"),
    "run_training_pipeline": ("numereng.features.training", "run_training"),
    "score_run_pipeline": ("numereng.features.training", "score_run"),
    "scrape_forum_posts": ("numereng.platform.forum_scraper", "scrape_forum_posts"),
}


def __getattr__(name: str):
    target = _LAZY_EXPORTS.get(name)
    if target is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module_name, attribute_name = target
    try:
        module = import_module(module_name)
    except ModuleNotFoundError as exc:
        missing = exc.name or ""
        if missing and not missing.startswith("numereng"):
            raise PackageError(f"runtime_dependency_missing:{missing}:run_uv_sync_extra_dev") from exc
        raise
    value = getattr(module, attribute_name)
    globals()[name] = value
    return value


def _agentic_research_api_module():
    return import_module("numereng.api._agentic_research")


def _agentic_research_feature_module():
    return import_module("numereng.features.agentic_research")


def research_init(*args, **kwargs):
    return _agentic_research_api_module().research_init(*args, **kwargs)


def research_program_list(*args, **kwargs):
    return _agentic_research_api_module().research_program_list(*args, **kwargs)


def research_program_show(*args, **kwargs):
    return _agentic_research_api_module().research_program_show(*args, **kwargs)


def research_run(*args, **kwargs):
    return _agentic_research_api_module().research_run(*args, **kwargs)


def research_status(*args, **kwargs):
    return _agentic_research_api_module().research_status(*args, **kwargs)


def get_research_program_record(*args, **kwargs):
    return _agentic_research_feature_module().get_research_program(*args, **kwargs)


def get_research_program_status(*args, **kwargs):
    return _agentic_research_feature_module().get_research_status(*args, **kwargs)


def init_research_program(*args, **kwargs):
    return _agentic_research_feature_module().init_research(*args, **kwargs)


def list_research_program_records(*args, **kwargs):
    return _agentic_research_feature_module().list_research_programs(*args, **kwargs)


def run_research_program(*args, **kwargs):
    return _agentic_research_feature_module().run_research(*args, **kwargs)


__all__ = [
    "AwsImageBuildPushRequest",
    "AwsTrainCancelRequest",
    "AwsTrainExtractRequest",
    "AwsTrainLogsRequest",
    "AwsTrainPullRequest",
    "AwsTrainStatusRequest",
    "AwsTrainSubmitRequest",
    "BaselineBuildRequest",
    "BaselineBuildResponse",
    "ExperimentArchiveRequest",
    "ExperimentArchiveResponse",
    "CloudAwsResponse",
    "CloudEc2Response",
    "CloudModalResponse",
    "DatasetToolsBuildDownsampleRequest",
    "DatasetToolsBuildDownsampleResponse",
    "DocsSyncRequest",
    "DocsSyncResponse",
    "EnsembleBuildRequest",
    "EnsembleComponentResponse",
    "EnsembleSelectRequest",
    "EnsembleSelectResponse",
    "EnsembleSelectionSourceRuleRequest",
    "EnsembleSelectionWinnerResponse",
    "EnsembleGetRequest",
    "EnsembleListRequest",
    "EnsembleListResponse",
    "EnsembleMetricResponse",
    "EnsembleResponse",
    "ExperimentCreateRequest",
    "ExperimentGetRequest",
    "ExperimentListRequest",
    "ExperimentListResponse",
    "ExperimentPackRequest",
    "ExperimentPackResponse",
    "ExperimentPromoteRequest",
    "ExperimentPromoteResponse",
    "ExperimentReportRequest",
    "ExperimentReportResponse",
    "ExperimentReportRowResponse",
    "ExperimentRunPlanRequest",
    "ExperimentRunPlanResponse",
    "ExperimentRunPlanWindowResponse",
    "ExperimentScoreRoundRequest",
    "ExperimentScoreRoundResponse",
    "ExperimentResponse",
    "ExperimentStatus",
    "ExperimentTrainRequest",
    "ExperimentTrainResponse",
    "ResearchBestRunResponse",
    "ResearchInitRequest",
    "ResearchInitResponse",
    "ResearchPhaseResponse",
    "ResearchPlannerContract",
    "ResearchProgramCatalogEntryResponse",
    "ResearchProgramConfigPolicyResponse",
    "ResearchProgramListRequest",
    "ResearchProgramListResponse",
    "ResearchProgramMetricPolicyResponse",
    "ResearchProgramPhaseResponse",
    "ResearchProgramRoundPolicyResponse",
    "ResearchProgramShowRequest",
    "ResearchProgramShowResponse",
    "ResearchProgramSource",
    "ResearchRoundResponse",
    "ResearchRunRequest",
    "ResearchRunResponse",
    "ResearchStatusRequest",
    "ResearchStatusResponse",
    "ResearchSupervisorStatus",
    "RunCancelRequest",
    "RunCancelResponse",
    "RunLifecycleRequest",
    "RunLifecycleResponse",
    "Ec2ConfigUploadRequest",
    "Ec2InitIamRequest",
    "Ec2InstallRequest",
    "Ec2LogsRequest",
    "Ec2PackageBuildUploadRequest",
    "Ec2ProvisionRequest",
    "Ec2PullRequest",
    "Ec2PushRequest",
    "Ec2S3CopyRequest",
    "Ec2S3ListRequest",
    "Ec2S3RemoveRequest",
    "Ec2SetupDataRequest",
    "Ec2StatusRequest",
    "Ec2TerminateRequest",
    "Ec2TrainPollRequest",
    "Ec2TrainStartRequest",
    "HealthResponse",
    "HpoNeutralizationRequest",
    "HpoObjectiveRequest",
    "HpoPlateauRequest",
    "HpoSamplerRequest",
    "HpoSearchSpaceSpecRequest",
    "HpoStoppingRequest",
    "HpoStudyCreateRequest",
    "HpoStudyGetRequest",
    "HpoStudyListRequest",
    "HpoStudyListResponse",
    "HpoStudyResponse",
    "HpoStudySpecResponse",
    "HpoStudyTrialsRequest",
    "HpoStudyTrialsResponse",
    "HpoTrialResponse",
    "ServeBlendRuleRequest",
    "ServeComponentInspectionResponse",
    "ServeComponentRequest",
    "ServeLiveBuildRequest",
    "ServeLiveBuildResponse",
    "ServeLiveSubmitRequest",
    "ServeLiveSubmitResponse",
    "ServeNeutralizationRequest",
    "ServePackageCreateRequest",
    "ServePackageInspectRequest",
    "ServePackageInspectResponse",
    "ServePackageListRequest",
    "ServePackageListResponse",
    "ServePackageResponse",
    "ServePackageScoreRequest",
    "ServePackageScoreResponse",
    "ServePackageSyncDiagnosticsRequest",
    "ServePackageSyncDiagnosticsResponse",
    "ServePickleBuildRequest",
    "ServePickleBuildResponse",
    "ServePickleUploadRequest",
    "ServePickleUploadResponse",
    "NumeraiCurrentRoundRequest",
    "NumeraiCurrentRoundResponse",
    "NumeraiDatasetDownloadRequest",
    "NumeraiDatasetDownloadResponse",
    "NumeraiDatasetListRequest",
    "NumeraiDatasetListResponse",
    "NumeraiModelsRequest",
    "NumeraiModelsResponse",
    "NumeraiForumScrapeResponse",
    "NumeraiTournament",
    "ScoreRunRequest",
    "ScoreRunResponse",
    "NeutralizationMode",
    "NeutralizeRequest",
    "NeutralizeResponse",
    "PackageError",
    "ModalDataSyncRequest",
    "ModalDataSyncResult",
    "ModalDeployRequest",
    "ModalDeployResult",
    "MonitorExperimentResponse",
    "MonitorLiveExperimentResponse",
    "MonitorLiveRunResponse",
    "MonitorRecentActivityResponse",
    "MonitorSnapshotRequest",
    "MonitorSnapshotResponse",
    "MonitorSourceResponse",
    "MonitorSummaryResponse",
    "RemoteConfigPushRequest",
    "RemoteConfigPushResponse",
    "RemoteDoctorRequest",
    "RemoteDoctorResponse",
    "RemoteExperimentLaunchRequest",
    "RemoteExperimentLaunchResponse",
    "RemoteExperimentMaintainRequest",
    "RemoteExperimentMaintainResponse",
    "RemoteExperimentPullFailureResponse",
    "RemoteExperimentPullRequest",
    "RemoteExperimentPullResponse",
    "RemoteExperimentStatusRequest",
    "RemoteExperimentStatusResponse",
    "RemoteExperimentStopRequest",
    "RemoteExperimentStopResponse",
    "RemoteExperimentSyncRequest",
    "RemoteExperimentSyncResponse",
    "RemoteRepoSyncRequest",
    "RemoteRepoSyncResponse",
    "RemoteTargetListRequest",
    "RemoteTargetListResponse",
    "RemoteTargetResponse",
    "RemoteVizBootstrapRequest",
    "RemoteVizBootstrapResponse",
    "RemoteVizBootstrapTargetResponse",
    "RemoteTrainLaunchRequest",
    "RemoteTrainLaunchResponse",
    "ModalTrainCancelRequest",
    "ModalTrainLogsRequest",
    "ModalTrainPullRequest",
    "ModalTrainStatusRequest",
    "ModalTrainSubmitRequest",
    "SubmissionRequest",
    "SubmissionResponse",
    "StoreDoctorRequest",
    "StoreDoctorResponse",
    "StoreIndexRequest",
    "StoreIndexResponse",
    "StoreInitRequest",
    "StoreInitResponse",
    "StoreMaterializeVizArtifactsFailureResponse",
    "StoreMaterializeVizArtifactsRequest",
    "StoreMaterializeVizArtifactsResponse",
    "StoreRunExecutionBackfillRequest",
    "StoreRunExecutionBackfillResponse",
    "StoreRunLifecycleRepairRequest",
    "StoreRunLifecycleRepairResponse",
    "StoreRebuildFailureResponse",
    "StoreRebuildRequest",
    "StoreRebuildResponse",
    "VizAppRequest",
    "TrainingEngineMode",
    "PostTrainingScoringPolicy",
    "TrainingProfile",
    "TrainRunRequest",
    "TrainRunResponse",
    "cloud_ec2_config_upload",
    "cloud_ec2_init_iam",
    "cloud_ec2_install",
    "cloud_ec2_logs",
    "cloud_ec2_package_build_upload",
    "cloud_ec2_provision",
    "cloud_ec2_pull",
    "cloud_ec2_push",
    "cloud_ec2_s3_copy",
    "cloud_ec2_s3_list",
    "cloud_ec2_s3_remove",
    "cloud_ec2_setup_data",
    "cloud_ec2_status",
    "cloud_ec2_terminate",
    "cloud_ec2_train_poll",
    "cloud_ec2_train_start",
    "cloud_aws_image_build_push",
    "cloud_aws_train_cancel",
    "cloud_aws_train_extract",
    "cloud_aws_train_logs",
    "cloud_aws_train_pull",
    "cloud_aws_train_status",
    "cloud_aws_train_submit",
    "cloud_modal_data_sync",
    "cloud_modal_deploy",
    "cloud_modal_train_cancel",
    "cloud_modal_train_logs",
    "cloud_modal_train_pull",
    "cloud_modal_train_status",
    "cloud_modal_train_submit",
    "_create_cloud_aws_managed_service",
    "_create_cloud_ec2_service",
    "_create_cloud_modal_service",
    "_create_numerai_client",
    "_default_dataset_dest_path",
    "archive_experiment_record",
    "baseline_build",
    "backfill_run_execution",
    "build_baseline_record",
    "cancel_run",
    "create_experiment_record",
    "dataset_tools_build_downsampled_full",
    "doctor_store",
    "download_numerai_dataset",
    "ensemble_build",
    "ensemble_get",
    "ensemble_list",
    "ensemble_select",
    "experiment_archive",
    "experiment_create",
    "experiment_get",
    "experiment_list",
    "experiment_pack",
    "experiment_promote",
    "experiment_report",
    "experiment_run_plan",
    "experiment_score_round",
    "experiment_train",
    "experiment_unarchive",
    "get_experiment_record",
    "get_health",
    "get_numerai_current_round",
    "get_run_lifecycle",
    "index_run",
    "init_store_db",
    "hpo_create",
    "hpo_get",
    "hpo_list",
    "hpo_trials",
    "neutralize_apply",
    "hpo_create_study",
    "hpo_get_study",
    "hpo_get_study_trials",
    "hpo_list_studies",
    "list_experiment_records",
    "build_ensemble_record",
    "select_ensemble_record",
    "build_monitor_snapshot",
    "get_ensemble_record_api",
    "get_run_lifecycle_record",
    "list_ensemble_records_api",
    "list_numerai_datasets",
    "list_numerai_models",
    "reconcile_run_lifecycles_record",
    "request_run_cancel_record",
    "scrape_forum_posts",
    "scrape_numerai_forum",
    "serve_live_build",
    "serve_live_submit",
    "serve_package_create",
    "serve_package_inspect",
    "serve_package_list",
    "serve_package_score",
    "serve_package_sync_diagnostics",
    "serve_pickle_build",
    "serve_pickle_upload",
    "promote_experiment_record",
    "pack_experiment_record",
    "rebuild_run_index",
    "report_experiment_record",
    "run_experiment_plan_record",
    "remote_config_push",
    "remote_bootstrap_viz",
    "remote_doctor",
    "remote_experiment_launch",
    "remote_experiment_maintain",
    "remote_experiment_pull",
    "remote_experiment_status",
    "remote_experiment_stop",
    "remote_experiment_sync",
    "remote_list_targets",
    "remote_repo_sync",
    "remote_train_launch",
    "research_init",
    "research_program_list",
    "research_program_show",
    "research_run",
    "research_status",
    "score_experiment_round_record",
    "score_run_pipeline",
    "run_training_pipeline",
    "score_run",
    "sync_docs",
    "store_backfill_run_execution",
    "store_doctor",
    "store_index_run",
    "store_init",
    "store_materialize_viz_artifacts",
    "store_repair_run_lifecycles",
    "store_rebuild",
    "create_viz_app",
    "run_training",
    "run_bootstrap_check",
    "init_research_program",
    "get_research_program_status",
    "run_research_program",
    "neutralize_prediction_artifact",
    "neutralize_run_prediction_artifact",
    "submit_predictions_file",
    "submit_predictions",
    "submit_run_predictions",
    "materialize_viz_artifacts",
    "train_experiment_record",
    "unarchive_experiment_record",
]
