"""Public surface for agentic research supervisor services."""

from numereng.features.agentic_research.utils.types import (
    CodexConfigPayload,
    CodexDecision,
    MutationChange,
    MutationProposal,
    ResearchBestRun,
    ResearchInitResult,
    ResearchLineageLink,
    ResearchLineageState,
    ResearchPathState,
    ResearchPhaseState,
    ResearchProgramCatalogEntry,
    ResearchProgramDetails,
    ResearchProgramState,
    ResearchRoundState,
    ResearchRunResult,
    ResearchStatusResult,
)
from numereng.features.agentic_research.run import (
    AgenticResearchError,
    AgenticResearchNotInitializedError,
    AgenticResearchValidationError,
    get_research_program,
    get_research_status,
    init_research,
    list_research_programs,
    run_research,
)

__all__ = [
    "AgenticResearchError",
    "AgenticResearchNotInitializedError",
    "AgenticResearchValidationError",
    "CodexConfigPayload",
    "CodexDecision",
    "MutationChange",
    "MutationProposal",
    "ResearchBestRun",
    "ResearchInitResult",
    "ResearchLineageLink",
    "ResearchLineageState",
    "ResearchPathState",
    "ResearchPhaseState",
    "ResearchProgramCatalogEntry",
    "ResearchProgramDetails",
    "ResearchProgramState",
    "ResearchRoundState",
    "ResearchRunResult",
    "ResearchStatusResult",
    "get_research_program",
    "get_research_status",
    "init_research",
    "list_research_programs",
    "run_research",
]
